media: public/media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, category, date ]
    fields:
      - name: category
        label: Category
        type: select
        options:
          values: [ old, hidden, post ]
          default: post
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: projects
    label: Projects
    type: collection
    path: '_projects'
    view:
      fields: [ title, era, status, hyperlink ]
    fields:
      - name: title
        label: Title
        type: string
      - name: era
        label: Era
        type: string
      - name: status
        label: Status
        type: select
        options:
          values: [ active, defunct, unknown ]
      - name: meta
        label: Meta
        type: text
      - name: hyperlink
        label: hyperlink
        type: string
      - name: image
        label: image
        type: image
      - name: published
        label: Published
        type: boolean
  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
