title: catskull.net
author: catskull
url: https://catskull.net
baseurl: "/"
description: > # description of the site (multiple lines allowed)
  mostly harmless

permalink: /:title.html

favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "catskull.net" # customize text for homepage link in post layout
  date_format: "%b %e %Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

image_prefix: /cdn-cgi/image/format=auto/

collections:
  newsletters:
    output: true
    permalink: /newsletter/:path
  recipes:
    output: true
  playlists:
    output: true
    permalink: /playlist/archive/:path
  archive:
    output: true
    permalink: /:title:output_ext

defaults:
  - scope:
      type: recipes
    values:
      layout: recipe
  - scope:
      type: playlists
    values:
      layout: playlist
  - scope:
      type: newsletters
    values:
      layout: post
