# Site settings
title: David DeGraw's homepage
email: bro@catskull.net
description: > # this means to ignore newlines until "baseurl:"
  This is the personal blog of David DeGraw. Rails developer.
  Electrical Engineering student.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://catskull.net" # the base hostname & protocol for your site
twitter_username: davidwdegraw
github_username:  catskull
timezone: America/Denver

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "David DeGraw"

permalink:        /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
